CREATE USER vendedor WITH PASSWORD 'senha_vendedor';
CREATE USER gerente WITH PASSWORD 'senha_gerente';

GRANT SELECT ON PRODUTO, PEDIDO TO vendedor;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUTO, PEDIDO, CLIENTE, FUNCIONARIO TO gerente;

GRANT SELECT ON Vw_Pedidos_Clientes TO vendedor;
GRANT SELECT ON Vw_Desempenho_Funcionarios TO gerente;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO vendedor;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gerente;